/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { WillManager } from "./WillManager";
export * as factories from "./factories";
export { WillManager__factory } from "./factories/WillManager__factory";
