/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Will } from "./Will";
export type { WillContract } from "./WillContract";
export * as factories from "./factories";
export { Will__factory } from "./factories/Will__factory";
export { WillContract__factory } from "./factories/WillContract__factory";
