/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, Signer, utils } from "ethers";
import type { EventFragment } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface WillInterface extends utils.Interface {
  functions: {};

  events: {
    "LogMessage(address,string)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "LogMessage"): EventFragment;
}

export interface LogMessageEventObject {
  sender: string;
  greeting: string;
}
export type LogMessageEvent = TypedEvent<
  [string, string],
  LogMessageEventObject
>;

export type LogMessageEventFilter = TypedEventFilter<LogMessageEvent>;

export interface Will extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: WillInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {};

  callStatic: {};

  filters: {
    "LogMessage(address,string)"(
      sender?: null,
      greeting?: null
    ): LogMessageEventFilter;
    LogMessage(sender?: null, greeting?: null): LogMessageEventFilter;
  };

  estimateGas: {};

  populateTransaction: {};
}
