/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Will__factory } from "./Will__factory";
export { WillContract__factory } from "./WillContract__factory";
